name: pipeman
description: A dart package to handle long and multistep tasks that require various pipelines and need concurrency.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^9.0.0
